apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://github.com/kostjaz/homelab-microk8s
    targetRevision: main
    path: clusters/homelab/apps/whoami

  destination:
    server: https://kubernetes.default.svc
    namespace: whoami

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
