apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  index.html: |
    <html>
      <head><title>Kostjaz Homelab</title></head>
      <body>
        <h1>OK</h1>
        <p>traefik works</p>
      </body>
    </html>
