apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: homepage
    namespace: homepage
    files:
      - assets/index.html
      - assets/termynal.css
      - assets/termynal.js
      - assets/favicon.svg
